before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install faraday -v 1.8.0
  - gem install dpl

stages:
  - staging
  - production

staging:
  stage: staging
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - staging

production:
  stage: production
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master